apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bds
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  namespace: bds
  name: redis-service
spec:
  selector:
    app: redis
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
