# Usa la imagen oficial de Golang como base
FROM golang:latest

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo go.mod y go.sum para descargar las dependencias
COPY go.mod .
COPY go.sum .

# Descarga las dependencias
RUN go mod download

# Copia el resto del código fuente al directorio de trabajo
COPY . .

# Compila la aplicación
RUN go build -o main .

# Expone el puerto 5000 en el contenedor
EXPOSE 5000

# Ejecuta la aplicación
CMD ["./main"]
