apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      name: deploy-consumer
  template:
    metadata:
      labels:
        name: deploy-consumer
    spec:
      containers:
      - name: consumer
        image: rubenralda/go-consumer:latest
        imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhubpull
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mi-aplicacion-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-consumer
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Escalar a más réplicas si el uso de CPU es mayor al 50%