# Usa la imagen oficial de Rust como base
FROM rust:latest as builder

RUN apt-get update && \
    apt-get install -y librdkafka-dev && \    
    apt-get install -y cmake && \
    rm -rf /var/lib/apt/lists/*

# Crea un directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia los archivos de tu aplicación al contenedor
COPY . .

# Compila la aplicación
RUN cargo build --release

# Crea una nueva imagen ligera
FROM ubuntu:latest

# Instala las dependencias necesarias
RUN apt-get update && apt-get install -y libssl-dev

# Copia el binario compilado desde la imagen de compilación a la imagen final
COPY --from=builder /usr/src/app/target/release/app-server /usr/local/bin/app-server

# Exponer el puerto que utiliza tu aplicación
EXPOSE 8080

# Comando para ejecutar tu aplicación cuando se inicie el contenedor
CMD ["app-server"]

# docker build -t rubenralda/rust_server:2.0 .
# docker push rubenralda/rust_server:2.0
# docker run -p 8080:8080 rubenralda/rust_server:2.0