apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-ruta
spec:
  selector:
    matchLabels:
      role: rust-ruta
  template:
    metadata:
      labels:
        role: rust-ruta
    spec:
      containers:
      - name: rust-cliente
        image: rubenralda/rust_cliente:2.0
        ports:
        - containerPort: 8000
      - name: rust-server
        image: rubenralda/rust_server:3.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-rust
spec:
  type: ClusterIP
  selector:
    role: rust-ruta
  ports:
  - name: rust-client-port
    port: 8000
    targetPort: 8000
  - name: rust-server-port
    port: 8080
    targetPort: 8080